### ISSUE TITLE
Update to Keras 2

### ISSUE THREAD

**Issue by tejasri19** [hbhasin/Image-Recognition-with-Deep-Learning#1]
Update your `fit_generator` call to the Keras 2 API: `fit_generator(<keras.pre..., epochs=50, class_weight="auto", validation_steps=203, validation_data=<keras.pre..., steps_per_epoch=40)`

**Comment by hbhasin** [comment]
Hello, Tejasri,

Sorry for the delay in my reply. Which particular Jupyter notebook were you
looking at? Please let me know.

Thanks,
Harpreet
